# Refer: https://github.com/envoyproxy/envoy/blob/main/examples/grpc-bridge
#
version: "3.7"

services:

  # Requires the build of the stubs first
  grpc-server:
    build:
      context: server
    image: envoy/kv-server:v1.0
    ports:
      - "8081:8081"
    networks:
      envoymesh:
        aliases:
          - kv-backend-service

  grpc-server-proxy:
    build:
      context: .
      dockerfile: Dockerfile-server
    image: envoy/front-proxy:v1.6
    networks:
      envoymesh:
        aliases:
          - kv-backend-proxy
    ports:
      - "8811:8811"

  # Requires the build of the stubs first
  grpc-client:
    build:
      context: client
    image: envoy/kv-client:v1.0
    environment:
      - CLIENT_PROXY=http://kv-client-proxy:9911
    networks:
      - envoymesh

  grpc-client-proxy:
    build:
      context: .
      dockerfile: Dockerfile-client
    image: envoy/be-service:v1.3
    networks:
      envoymesh:
        aliases:
          - kv-client-proxy
    ports:
      - "9911:9911"

networks:
  envoymesh: {}
