#
# Created by zhengjn, at 2018-06-02
# Ref: https://docs.docker.com/compose/compose-file/compose-file-v2
#
version: "2"

services:
  datavol:
    image: zjtools
    container_name: datavol
    volumes:
      - ~/Workspaces/ZJWorkspaces/dockerapps/data:/home/zhengjin/data
    networks:
      - zj_network

  redisserver:
    image: zjredis
    container_name: myredis
    expose:
      - "6379"
    network:
      - zj_network

  mockserver:
    image: zjmock
    container_name: mymock
    expose: 
      - "17891"
    depends_on:
      - redisserver
    volumes: # load conf when run container
      - ~/Workspaces/ZJWorkspaces/dockerapps/configs/mock_conf.json usr/local/bin/
    networks:
      - zj_network

  vueserver:
    image: zjvue:latest
    container_name: myvue
    expose: 
      - "8081"
    networks:
      - zj_network

  nginxserver:
    image: zjnginx
    container_name: mynginx
    depends_on:
      - datavol
      - mockserver
      - vueserver
      - redisserver
    ports:
      - "8080:80"
    volumes_from:
      - datavol
    volumes: # load conf when run container
      - ~/Workspaces/ZJWorkspaces/dockerapps/configs/nginx_conf/nginx.conf.json /etc/nginx/
    networks:
      - zj_network

networks:
  zj_network:
    driver: bridge
