#
# Created by zhengjn, at 2019-09-03
#
# Pre-conditions:
# 1. host entry: 127.0.0.1 mockserver.test.com vueserver.test.com
# 2. sh prepare_files.sh, and sh setup.sh for each service in docker env.
#
version: "2.1"

services:
  vueserver:
    image: tomcat:latest
    container_name: vue3
    volumes:
      - "/tmp/dist:/tmp/dist"
    ports:
      - "8080:8080"

  mockserver:
    image: mockserver:latest
    container_name: mockserver
    volumes:
      - "/tmp/mockserver:/tmp/mockserver"
    ports:
      - "17891:17891"

  openresty:
    image: openresty/openresty:1.15.8.1-1-alpine-fat-nosse42
    container_name: openresty
    environment:
      - "CONF_HOME=/etc/nginx/conf.d"
    volumes:
      - "/tmp/openrestyapp:/tmp/openrestyapp"
    ports:
      - "8081:80"
    depends_on:
      - vueserver
      - mockserver

