#
# Create at 2019-01-13, build etcd cluster
# Refer: https://github.com/appcelerator-archive/docker-etcd
#
version: "3.3"

networks:
  etcd:
    external: true

services:
  etcd:
    image: bigdata/etcd
    networks:
      - etcd
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 3
    deploy:
      mode: replicated
      replicas: 3
