FROM nginx

# created at 2018-06-02
MAINTAINER zivieira@163.com

ADD nginx_conf/nginx.conf /etc/nginx/nginx.conf
ADD nginx_conf/proxy.conf /etc/nginx/
ADD webapps /home/zhengjin

EXPOSE 8080

CMD nginx -g 'daemon off;'

