#
# Create at 2019-01-23, build pod with configmap.
#
kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2019-01-23T19:14:38Z
  name: k8s-test-config
  namespace: k8s-test-ns
data:
  # example of a simple property defined using --from-literal
  property.1: hello
  property.2: world
  # example of a complex property defined using --from-file
#  example.property.file: 
#    property.1=value-1
#    property.2=value-2

---
