# Create at 2020-08-13, build vue frontend + flask backend + mysql + admin demo env.
# Use root/example as user/password credentials
#
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ${HOME}/Downloads/tmps/docker_vols/mysql:/var/lib/mysql
    # ports:
    #   - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8089:8080
    depends_on:
      - db

  backend:
    image: login-backend:v1
    container_name: backend
    ports:
      - 12340:12340
    depends_on:
      - db
    environment:
      - MYSQL=db
      - FLASK_ENV=prod
    volumes:
      - ${HOME}/Downloads/tmps/docker_vols/backend:/app
    command: [/bin/bash, -c, sleep 3 && cd /app && python app.py]

  frontend:
    image: nginx
    container_name: frontend
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend
