# Refer: https://github.com/envoyproxy/envoy/blob/main/examples/cors/backend
#
version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    image: envoy/front-proxy:v1.2
    networks:
      - envoymesh
    ports:
      - "8002:8000"
      - "8003:8001"

  backend-service:
    build:
      context: .
      dockerfile: Dockerfile-service
    image: envoy/be-service:v1.2
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - backendservice

networks:
  envoymesh: {}
