# Refer: https://github.com/envoyproxy/envoy/blob/main/examples/dynamic-config-fs
#
version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    image: envoy/front-proxy:v1.4
    depends_on:
    - service1
    - service2
    ports:
    - 10000:10000
    - 19000:19000

  service1:
    image: jmalloc/echo-server
    hostname: service1

  service2:
    image: jmalloc/echo-server
    hostname: service2
