#
# Create at 2020-05-17, build Gitlab + Jenkins cicd env.
#
# compose file reference:
# https://docs.docker.com/compose/compose-file/#restart
#
version: "3"

services:
  jenkins:
    image: fixiu/jenkins-pipeline
    hostname: jenkins
    container_name: jenkins
    restart: "no"
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /Users/zhengjin/cicd/jenkins_home:/var/jenkins_home
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai

  gitlab:
    image: gitlab/gitlab-ce:12.10.6-ce.0
    hostname: gitlab.example.com
    container_name: gitlab
    restart: "no"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      # cannot mount to local /tmp
      - /Users/zhengjin/cicd/gitlab/config:/etc/gitlab
      - /Users/zhengjin/cicd/gitlab/logs:/var/log/gitlab
      - /Users/zhengjin/cicd/gitlab/data:/var/opt/gitlab
