#
# Create at 2019-06-04, build OpenResty (nginx + lua) env. 
#
version: "3"

services:
  openresty:
    image: openresty/openresty:1.15.8.1-1-alpine-fat-nosse42
    container_name: openresty 
    environment:
      - CONF_HOME=/etc/nginx/conf.d
    volumes:
      - /tmp/openrestyapp:/tmp/openrestyapp
    ports:
      - 8080:80
    networks:
      - openresty-net

  redis:
    image: redis:4.0
    container_name: redis
    networks:
      - openresty-net
    command:
      - "redis-server"
      - "--appendonly yes"
    ports:
      - 6379:6379

networks:
  openresty-net:
    driver: bridge

