#
# Create at 2019-5-10, create elk + nginx env. 
#
version: "3.2"

services:
  elasticsearch:
    image: elasticsearch:6.7.2 
    container_name: elasticsearch
    ports:
    - 9200:9200
    volumes:
      - /tmp/elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:6.7.2
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - 4560:4560
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/configs/logstash.conf:/etc/logstash.conf
    command: [logstash, -f, /etc/logstash.conf]

  kibana:
    image: kibana:6.7.2
    container_name: kibana
    depends_on:
      - logstash
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - kibana
    ports:
      - 90:80
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:4560
        tag: nginx
