#
# Create at 2019-03-24, build hadoop (hdfs + mapreduce + yarn) env.
# Java version: 1.7
#
# access web ui:
# hdfs: http://localhost:50070
# yarn: http://localhost:8088
#
version: '3.1'

services:
  hadoop:
    image: sequenceiq/hadoop-docker
    container_name: hadoop-yarn
    restart: "no"
    ports:
      - 9001:9000
      - 50070:50070  # namenode
      - 50075:50075  # datanode
      - 8088:8088  # yarn
    #command: ["/etc/bootstrap.sh", "-d"]
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/usr/local/hadoop/bin"
    volumes:
      - "/tmp/hadoop_test:/tmp/hadoop_test"
