#
# Create at 2019-01-09, build kafka env.
# 
# Condition: add /etc/hosts: 192.168.1.3 zjmbp
#
version: '3.2'

services:
  zookeeper:
    container_name: "test-zookeeper"
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: "test-kafka"
    image: wurstmeister/kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://zjmbp:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
