#
# Create at 2019-01-28, build granfna + prometheus + alertmanager + 2 nodeexporters env.
#
# prometheus: http://localhost:9090/graph
# alertmanager: http://localhost:9093/#/alerts
# granfna: http://localhost:3000/
#
version: "3"

services:
  granfna:
    image: grafana/grafana:5.4.3
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/data/granfna:/var/lib/grafana

  prometheus:
    # use custom prometheus.yml and alert.rules
    image: prom/prometheus:v2.7.1
    container_name: prometheus
    depends_on:
      - alertmanager
      - nodeexporter1
      - nodeexporter2
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/configs/prometheus_conf:/etc/prometheus
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/data/prometheus:/prometheus
    ports:
      - "9090:9090"

  alertmanager:
    # use default alertmanager.yml in container
    image: prom/alertmanager:v0.16.0
    container_name: alertmanager
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/data/alertmanager:/alertmanager
    ports:
      - "9093:9093"

  nodeexporter1:
   image: prom/node-exporter:v0.17.0
   container_name: nodeexporter1
#  ports:
#    - "9100:9100"

  nodeexporter2:
   image: prom/node-exporter:v0.17.0
   container_name: nodeexporter2
#  ports:
#    - "9100:9100"
