#
# Create at 2019-01-28, build prometheus + alertmanager + nodeexporter env.
#
version: "3"

services:
  prometheus:
    # use custom prometheus.yml and alert.rules
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - alertmanager
      - nodeexporter
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/configs/prometheus_conf:/etc/prometheus
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  alertmanager:
    # use default alertmanager.yml in container
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/data/alertmanager:/alertmanager

  nodeexporter:
   image: prom/node-exporter
   container_name: nodeexporter
   ports:
     - "9100:9100"
