#
# Create at 2019-02-22, build grafana + prometheus + redis + redis_exporter + node_exporter env.
#
# prometheus: http://localhost:9090/graph
#
version: "3"

services:
  granfna:
    image: grafana/grafana:5.4.3
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/data/granfna:/var/lib/grafana

  prometheus:
    # use custom prometheus.yml and alert.rules
    image: prom/prometheus:v2.7.1
    container_name: prometheus
    depends_on:
      - redis
      - redis_exporter
      - node_exporter
    volumes:
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/configs/prometheus_conf:/etc/prometheus
      - ${HOME}/Workspaces/zj_work_workspace/dockerapps/data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus2.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  node_exporter:
   image: prom/node-exporter:v0.17.0
   container_name: node_exporter
#  ports:
#    - "9100:9100"

  redis:
    image: redis:4.0
    container_name: redis
    command:
      - "redis-server"
      - "--appendonly yes"
    ports:
      - "6379:6379"

  redis_exporter:
    image: oliver006/redis_exporter:v0.28.0
    container_name: redis_exporter
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis://redis:6379
#   ports:
#     - "9121:9121"
