#
# Create at 2018-12-17
# Build selenium grid debug (with vnc record enabled) to run ui test parallel. 
# Refer: https://github.com/SeleniumHQ/docker-selenium
#
# Run commands:
# $ docker-compose -f selenium-hub-compose-debug.yaml up -d
# $ docker-compose -f selenium-hub-compose-debug.yaml down
#
# selenium hub check: http://localhost:4444/wd/hub/status
#
version: "3"

services:
  selenium-hub:
    image: selenium/hub:3.141
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host 0.0.0.0", "--port 4444"]
      interval: 15s
      timeout: 30s
      retries: 5 

  selenium-node-chrome:
    image: selenium/node-chrome-debug:3.141 
    container_name: selenium-node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1 # vnc without pwd, uri: 127.0.0.1:5901
    ports:
      - "5901:5900"
    networks:
      - selenium-grid
    shm_size: 1G

  selenium-node-firefox:
    image: selenium/node-firefox-debug:3.141
    container_name: selenium-node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1
    ports:
      - "5902:5900"
    networks:
      - selenium-grid
    shm_size: 1G

networks:
  selenium-grid:
    driver: bridge
