#
# Create at 2018-12-17
# Build selenium grid enviroment to run ui test parallel. 
# selenium hub check: http://localhost:4444/wd/hub/status
#
# Run commands:
# $ docker-compose -f selenium-hub-compose.yaml up -d
# $ docker-compose -f selenium-hub-compose.yaml down
#
version: "3"

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  selenium-node-chrome:
    image: selenium/node-chrome-debug 
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=false
    ports:
      - "5901:5900"
    networks:
      - selenium-grid
    shm_size: 1G

  selenium-node-firefox:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=false
    ports:
      - "5902:5900"
    networks:
      - selenium-grid
    shm_size: 1G

networks:
  selenium-grid:
    driver: bridge
