#
# Create at 2020-11-04, build nginx (https) + echoserver env.
#
version: '3.2'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
    # - 8080:80
      - 8443:443
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ${HOME}/Workspaces/zj_repos/zj_work_workspace/dockerapps/configs/https_conf/default.conf:/etc/nginx/conf.d/default.conf
      - ${HOME}/.ssl/server.key:/etc/nginx/ssl/server.key
      - ${HOME}/.ssl/server.crt:/etc/nginx/ssl/server.crt
    depends_on:
      - echoserver

  echoserver:
    image: cilium/echoserver
    container_name: echoserver
    restart: always
    # ports:
    #   - 8080:8080
    #   - 8443:8443
