#
# Ceate at 2019-02-26, build redis env, and redis_exporter and busybox as sidecar for monitor.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: redis
  name: redis
  namespace: k8s-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0
        args:
        - "--appendonly yes"
        ports:
        - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter:v0.29.0
        #command:
        #- "./redis_exporter"
        args:
        - "-redis.addr=localhost:6379"
        ports:
        - containerPort: 9121
      - name: busybox
        image: busybox:1.30
        imagePullPolicy: IfNotPresent
        command: ["sh"]
        args: ["-c", "while true; do echo $(date +'%Y-%m-%d_%H:%M:%S') 'busybox is running ...'; sleep 8; done;"]

---