#
# Create at 2019-02-26, build services for reids and redis_exporter.
#
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: k8s-monitor
  labels:
    svc: "redis"
spec:
  ports:
    - name: http-redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: http-exporter
      port: 9121
      protocol: TCP
      targetPort: 9121
  selector:
    run: redis
  type: ClusterIP

---