image:
  tag: 7.9.4-community

ingress:
  enabled: true
  hosts:
    - name: sonar.airpay-qa-testdev.i.test.airpay.in.th
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"    

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 512Mi

# use default "standard" storageclass (minikube default-storageclass addson is enabled)
persistence:
  enabled: true
  size: 5Gi

postgresql:
  persistence:
    enabled: true
    size: 10Gi
