kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-nodeport
  namespace: kube-test-ns
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 32080
    - name: https
      port: 443
      targetPort: https
      nodePort: 32443

---
