# Create at 2020-11-04, build nginx + https env.
#
# Create cert:
# openssl genrsa -out tls.key 2048
# openssl req -new -x509 -key tls.key -days 256 -out tls.crt -subj /C=CN/ST=GuangDong/L=Guangzhou/O=DevOps/CN=nginx.default.k8s
#
# Create secret:
# kubectl create secret tls nginx-ingress-secret --cert=tls.crt --key=tls.key
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-tls
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - nginx.default.k8s
    secretName: nginx-ingress-secret
  rules:
  - host: nginx.default.k8s
    http:
      paths:
      - path:
        backend:
          serviceName: nginx-svc
          servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  selector:
    app: nginx
    release: canary
  type: ClusterIP
  ports:
  - name: http
    targetPort: 80
    port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      release: canary
  template:
    metadata:
      labels:
        app: nginx
        release: canary
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.3-alpine
        ports:
        - name: http
          containerPort: 80
