# Refer: 
# docs: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy#install-sandboxes-front-proxy
# github: https://github.com/envoyproxy/envoy/tree/main/examples/front-proxy
#
version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    image: envoy/front-proxy:v1.0
    networks:
      - envoymesh
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    image: envoy/be-service:v1.0
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=1

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    image: envoy/be-service:v1.0
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=2

networks:
  envoymesh: {}
