apiVersion: v1
kind: PersistentVolume
metadata:
  name: qa-testdev-local-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: qa-testdev-local-storage
  local:
    path: /data/logs/qa-testdev-local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node10
