apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qa-testdev-claim
  namespace: airpay-qa-testdev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: qa-testdev-local-storage
  resources:
    requests:
      storage: 30Gi
