#
# Create at 2019-01-29, refer:
# https://github.com/bibinwilson/kubernetes-prometheus/blob/master/prometheus-service.yaml
#
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus
  type: NodePort  
  ports:
    - port: 9090
      targetPort: 9090 
      nodePort: 30090

---
