#
# Create at 2019-02-21, minikube quick start demo.
# Create by: kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080 --dry-run -o yaml > echo_server_deploy_conf.yml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hello-minikube
  name: hello-minikube
  namespace: mini-test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-minikube
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-minikube
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.10
        imagePullPolicy: IfNotPresent
        name: hello-minikube
        ports:
        - containerPort: 8080
        resources: {}
status: {}

---
