# Deploy echo service.
#
# Ingress refer:
# https://kubernetes.io/docs/concepts/services-networking/ingress/
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: echoserverv1
  name: echoserverv1
  namespace: k8s-test
spec:
  rules:
  - host: k8s.echo.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserverv1
            port:
              number: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: echoserverv1
  namespace: k8s-test
spec:
  selector:
    name: echoserverv1
  type: ClusterIP
  ports:
  - name: echoserverv1
    port: 8080
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserverv1
  namespace: k8s-test
  labels:
    name: echoserverv1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: echoserverv1
  template:
    metadata:
      labels:
        name: echoserverv1
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.10
        name: echoserverv1
        ports:
        - containerPort: 8080
          name: echoserverv1
