# Deploy echo service with canary settings.
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    nginx.ingress.kubernetes.io/canary-by-header: "x-canary"
  labels:
    app: echoserverv2
  name: echoserverv2
  namespace: k8s-test
spec:
  rules:
  - host: k8s.echo.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserverv2
            port:
              number: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: echoserverv2
  namespace: k8s-test
spec:
  selector:
    name: echoserverv2
  type: ClusterIP
  ports:
  - name: echoserverv2
    port: 8080
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserverv2
  namespace: k8s-test
  labels:
    name: echoserverv2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: echoserverv2
  template:
    metadata:
      labels:
        name: echoserverv2
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.10
        name: echoserverv2 
        ports:
        - containerPort: 8080
          name:  echoserverv2
