# Refer:
# docs: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache
# github: https://github.com/envoyproxy/envoy/blob/main/examples/cache
#
version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    image: envoy/front-proxy:v1.1
    networks:
      - envoymesh
    ports:
      - "8000:8000"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    image: envoy/be-service:v1.1
    volumes:
      - ./responses.yaml:/etc/responses.yaml
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=1

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service
    image: envoy/be-service:v1.1
    volumes:
      - ./responses.yaml:/etc/responses.yaml
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=2

networks:
  envoymesh: {}
