#
# Created by zhengjn, at 2019-09-03
#
# Pre-conditions:
# 1. cp dockerapps/configs/vue3_nginx_conf/*.conf /tmp/openrestyapp
# 2. host entry: 127.0.0.1 mockserver.test.com vueserver.test.com
#
version: "2.1"

services:
  vueserver:
    image: tomcat:latest
    container_name: vue3
    volumes:
      - "/tmp/dist:/usr/local/tomcat/webapps/dist"
    #ports:
    #  - "8080:8080"

  mockserver:
    image: mockserver:latest
    container_name: mockserver
    #ports:
    #  - "17891:17891"

  openresty:
    image: openresty/openresty:1.15.8.1-1-alpine-fat-nosse42
    container_name: openresty
    environment:
      - "CONF_HOME=/etc/nginx/conf.d"
    volumes:
      - "/tmp/openrestyapp:/tmp/openrestyapp"
    ports:
      - "8081:80"
    depends_on:
      - vueserver
      - mockserver

