#
# Created by zhengjn, at 2018-06-02
# Ref: https://docs.docker.com/compose/compose-file/compose-file-v2
#
version: "2"

services:
  datavol:
    image: zjtools
    container_name: datavol
    volumes:
      - ~/Workspaces/ZJWorkspaces/dockerapps/data/webapps:/home/zhengjin/webapps
      - ~/Workspaces/ZJWorkspaces/dockerapps/data/redisdump:/data
    networks:
      - zj_network

  redisserver:
    image: zjredis
    container_name: myredis
    expose:
      - "6379"
    volumes_from:
      - datavol
    networks:
      - zj_network

  mockserver:
    image: zjmock
    container_name: mymock
    expose: 
      - "17891"
    depends_on:
      - redisserver
    volumes: # load conf
      - ~/Workspaces/ZJWorkspaces/dockerapps/configs/mock_conf.json:/usr/local/bin/mock_conf.json
    networks:
      - zj_network

  vueserver:
    image: zjvue:latest
    container_name: myvue
    expose: 
      - "8080"
    networks:
      - zj_network

  nginxserver:
    image: zjnginx
    container_name: mynginx
    depends_on:
      - mockserver
      - vueserver
    ports:
      - "8081:80"
    volumes_from:
      - datavol
    volumes:
      - ~/Workspaces/ZJWorkspaces/dockerapps/configs/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - zj_network

networks:
  zj_network:
    driver: bridge
